### ISSUE TITLE
fix run_model

### ISSUE THREAD

**Issue by EnnioEnnio** [EnnioEnnio/dl_facemask_detector#24]
note @Toalaah 

https://github.com/EnnioEnnio/dl_facemask_detector/tree/483dddf44b815ed8ee81c234e22e7f5751fddec5

when running on a GPU there seem to be a mistake happening. I have no idea atm, maybe u have one? 
If no my suggestion: Remove device selection, thus drop CPU support for run_model.py and state in the readme that a GPU is necessary (because with this fix GPU works)

Error: 
```python run_model.py --image=/dhc/home/ennio.strohauer/dl_facemask_detector/testbild.png
Using cache found in /dhc/home/ennio.strohauer/.cache/torch/hub/pytorch_vision_v0.10.0
/dhc/home/ennio.strohauer/conda3/envs/facemask/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/dhc/home/ennio.strohauer/conda3/envs/facemask/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
[INFO] [run_model] Model path: /dhc/home/ennio.strohauer/dl_facemask_detector/ResNet-trained.pt
[INFO] [util] Using computation device: NVIDIA GeForce RTX 2080 Ti * 1
Traceback (most recent call last):
  File "/dhc/home/ennio.strohauer/dl_facemask_detector/run_model.py", line 38, in <module>
    run_model(model, args.image)
  File "/dhc/home/ennio.strohauer/dl_facemask_detector/run_model.py", line 16, in run_model
    neural_net(image)).item() > 0.5 else "unmasked")
  File "/dhc/home/ennio.strohauer/conda3/envs/facemask/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/dhc/home/ennio.strohauer/conda3/envs/facemask/lib/python3.10/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/dhc/home/ennio.strohauer/conda3/envs/facemask/lib/python3.10/site-packages/torchvision/models/resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
  File "/dhc/home/ennio.strohauer/conda3/envs/facemask/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/dhc/home/ennio.strohauer/conda3/envs/facemask/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/dhc/home/ennio.strohauer/conda3/envs/facemask/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor```

**Comment by Toalaah** [comment]
@EnnioEnnio please see the linked commit / PR. I unfortunately do not have access to a CUDA-enabled machine atm so you would need to test this fix.
